#!/usr/bin/env python3
"""Self-host the faces a cut of the site uses.

Newsreader, Geist and Geist Mono are all SIL OFL. Google serves each family
split into subsets; only latin and latin-ext are kept, since no page here
sets Greek, Cyrillic or Vietnamese. Re-run to refresh:

    python3 tools/fetch_fonts.py            # the ink cut
    python3 tools/fetch_fonts.py teeter     # the Teeter site

Fontshare and jsDelivr are unreachable from the build container, so the
Google Fonts library is the whole of what can be installed here.
"""
import os
import re
import sys
import urllib.parse
import urllib.request

UA = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"}
KEEP = ("latin", "latin-ext")

# Each preset is one site's faces. `python3 tools/fetch_fonts.py teeter`
PRESETS = {
    "ink": {
        "fonts": "ink/assets/fonts",
        "css": "ink/css/fonts.css",
        "families": [
            ("Newsreader", "ital,opsz,wght@0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,400"),
            ("Geist", "wght@400;500;600"),
            ("Geist+Mono", "wght@400;500"),
        ],
        "names": "Newsreader, Geist and Geist Mono",
    },
    # Archivo is fetched as one variable font across its width and weight
    # axes, so the expanded titles and the normal-width text are the same
    # file. B612 Mono was designed with Airbus for cockpit displays.
    "teeter": {
        "fonts": "teeter/assets/fonts",
        "css": "teeter/css/fonts.css",
        "families": [
            ("Archivo", "wdth,wght@62..125,100..900"),
            ("B612+Mono", "wght@400;700"),
        ],
        # Characters the drawings set that fall outside Google's latin
        # subset. B612 Mono has all of them; Archivo has no theta, so these
        # only ever appear in mono.
        "extra": {"B612+Mono": "\u03b8\u2080\u2192\u221a\u2248\u00b1\u2220\u00d7\u2264\u2265"},
        "names": "Archivo and B612 Mono",
    },
}


def header(names):
    return f"""/* Self-hosted subsets of {names} (all SIL OFL).
   Latin and latin-ext only; the Greek, Cyrillic and Vietnamese subsets
   Google serves are dropped, since no page here sets them. Generated by
   tools/fetch_fonts.py — edit that, not this. */

"""


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=30) as f:
        return f.read() if binary else f.read().decode()


def main():
    preset = PRESETS[sys.argv[1] if len(sys.argv) > 1 else "ink"]
    out_fonts, out_css = preset["fonts"], preset["css"]
    os.makedirs(out_fonts, exist_ok=True)
    os.makedirs(os.path.dirname(out_css), exist_ok=True)
    blocks_out = []

    for family, axis in preset["families"]:
        css = fetch(f"https://fonts.googleapis.com/css2?family={family}:{axis}&display=swap")
        # Each @font-face is preceded by a /* subset */ comment naming its coverage.
        for block, subset in re.findall(r"(/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{.*?\})", css, re.S):
            if subset not in KEEP:
                continue
            url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
            local = f"{family.lower().replace('+', '-')}-{url.rsplit('/', 1)[-1]}"
            with open(os.path.join(out_fonts, local), "wb") as f:
                f.write(fetch(url, binary=True))
            blocks_out.append(block.replace(url, f"../assets/fonts/{local}"))

    for family, chars in preset.get("extra", {}).items():
        for weight in (400, 700):
            q = urllib.parse.quote(chars)
            css = fetch(f"https://fonts.googleapis.com/css2?family={family}:wght@{weight}&text={q}&display=swap")
            url = re.search(r"url\((https://[^)]+)\)", css).group(1)
            local = f"{family.lower().replace('+', '-')}-extra-{weight}.woff2"
            with open(os.path.join(out_fonts, local), "wb") as f:
                f.write(fetch(url, binary=True))
            ranges = ", ".join(f"U+{ord(c):04X}" for c in chars)
            blocks_out.append(
                "/* extra: characters outside the latin subset */\n@font-face {\n"
                f"  font-family: '{family.replace('+', ' ')}';\n  font-style: normal;\n"
                f"  font-weight: {weight};\n  font-display: swap;\n"
                f"  src: url(../assets/fonts/{local}) format('woff2');\n"
                f"  unicode-range: {ranges};\n}}")

    with open(out_css, "w") as f:
        f.write(header(preset["names"]) + "\n".join(blocks_out) + "\n")
    print(f"{len(blocks_out)} faces -> {out_fonts}")


if __name__ == "__main__":
    main()
