#!/usr/bin/env python3
"""Self-host the three faces the ink cut uses.

Newsreader, Geist and Geist Mono are all SIL OFL. Google serves each family
split into subsets; only latin and latin-ext are kept, since no page here
sets Greek, Cyrillic or Vietnamese. Re-run to refresh:

    python3 tools/fetch_fonts.py

Fontshare and jsDelivr are unreachable from the build container, so the
Google Fonts library is the whole of what can be installed here.
"""
import os
import re
import urllib.request

UA = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"}
KEEP = ("latin", "latin-ext")
OUT_FONTS = "ink/assets/fonts"
OUT_CSS = "ink/css/fonts.css"

FAMILIES = [
    ("Newsreader", "ital,opsz,wght@0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,400"),
    ("Geist", "wght@400;500;600"),
    ("Geist+Mono", "wght@400;500"),
]

HEADER = """/* Self-hosted subsets of Newsreader, Geist and Geist Mono (all SIL OFL).
   Latin and latin-ext only; the Greek, Cyrillic and Vietnamese subsets
   Google serves are dropped, since no page here sets them. Generated by
   tools/fetch_fonts.py — edit that, not this. */

"""


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=30) as f:
        return f.read() if binary else f.read().decode()


def main():
    os.makedirs(OUT_FONTS, exist_ok=True)
    os.makedirs(os.path.dirname(OUT_CSS), exist_ok=True)
    blocks_out = []

    for family, axis in FAMILIES:
        css = fetch(f"https://fonts.googleapis.com/css2?family={family}:{axis}&display=swap")
        # Each @font-face is preceded by a /* subset */ comment naming its coverage.
        for block, subset in re.findall(r"(/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{.*?\})", css, re.S):
            if subset not in KEEP:
                continue
            url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
            local = f"{family.lower().replace('+', '-')}-{url.rsplit('/', 1)[-1]}"
            with open(os.path.join(OUT_FONTS, local), "wb") as f:
                f.write(fetch(url, binary=True))
            blocks_out.append(block.replace(url, f"../assets/fonts/{local}"))

    with open(OUT_CSS, "w") as f:
        f.write(HEADER + "\n".join(blocks_out) + "\n")
    print(f"{len(blocks_out)} faces -> {OUT_FONTS}")


if __name__ == "__main__":
    main()
